### ISSUE TITLE
'LLG' object has no attribute 'driver'

### ISSUE THREAD

**Issue by kausik6das3** [computationalmodelling/fidimag#121]
I am trying "Fidimag: A Basic Simulation" Through fidimag/notebook  Docker as it is in documentation but when I give

sim.driver.alpha = 0.5
sim.driver.gamma = 2.211e5

command I got following error

AttributeErrorTraceback (most recent call last)
<ipython-input-29-5e31fa166389> in <module>()
----> 1 sim.driver.alpha = 0.5
      2 sim.driver.gamma = 2.211e5

AttributeError: 'LLG' object has no attribute 'driver'

**Comment by rpep** [comment]
Hi @kausik6das3 

This issue should now be fixed, but I haven't yet updated the Docker image on Docker hub because I don't have the correct permissions. What you can try to do is:

1) Clone fidimag with:
> git clone https://github.com/computationalmodelling/fidimag
2) cd to fidimag/docker/notebook
3) type 'make', which should build the new notebook image with the master branch of Fidimag installed.
4) Now run:
> docker run -v `pwd`:/io -p 30008:8888 fidimag/notebook

5) You should get some output which ends like this:
```
[C 06:36:46.251 NotebookApp]

    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://(791adcb5ab27 or 127.0.0.1):8888/?token=eb76b9f5d2182e49039b6eead60a2241235062afefc1c689
```

On your computer, go to the URL:
127.0.0.1:30008/?token=(copy the token from above here)

**Comment by kausik6das3** [comment]
> I am trying "Fidimag: A Basic Simulation" Through fidimag/notebook Docker as it is in documentation but when I give
> 
> sim.driver.alpha = 0.5
> sim.driver.gamma = 2.211e5
> 
> command I got following error
> 
> AttributeErrorTraceback (most recent call last)
> in ()
> ----> 1 sim.driver.alpha = 0.5
> 2 sim.driver.gamma = 2.211e5
> 
> AttributeError: 'LLG' object has no attribute 'driver'

After doing so I got this problem
![screenshot from 2018-10-11 14-08-27](https://user-images.githubusercontent.com/32133686/46791632-320b7900-cd5f-11e8-86e7-bed242c6347b.png)

**Comment by hardidi** [comment]
Any chance the docker image will be updated in a near future, for us poor Windows users who can't build a new Docker image? Thanks :-)

**Comment by kausik6das3** [comment]
![screenshot from 2018-10-12 12-07-00](https://user-images.githubusercontent.com/32133686/46852082-59be1800-ce17-11e8-9271-9998f560e3b8.png)
