### ISSUE TITLE
'LLG' object has no attribute 'driver'

### ISSUE THREAD

**Issue by longlong-zhang** [computationalmodelling/fidimag#143]
Hello all ,
  I met a new problem when l use fidimag in docker. Hoping for any hints you can give
![微信截图_20200427192827](https://user-images.githubusercontent.com/50805242/80367241-51c0ae80-88bd-11ea-8b3a-6b4be7524078.png)

**Comment by davidcortesortuno** [comment]
It seems you are using an older version of Fidimag. Which Docker file did you use to run Fidimag?
It could also be that `sim` is not well defined in the example you mention, which file are you running?

**Comment by longlong-zhang** [comment]
### hello professor,
   ### I just follow the instruction of Fidimag documentation to set  up my docer environment,and then i try the example "spin current driven domain wall ".sadly, it bring some problems just as i mentioned last time.


![微信截图_20200429145548](https://user-images.githubusercontent.com/50805242/80568811-4a6ae380-8a2a-11ea-822f-80ddb679a4ea.png)
![22](https://user-images.githubusercontent.com/50805242/80568839-56ef3c00-8a2a-11ea-813c-44bd961a1527.png)

**Comment by davidcortesortuno** [comment]
Hi, I see.The docs and docker image are outdated and need to be updated. 
I updated the Binder scripts in the Github repository, so if you press the Binder button at the top of the README file, you can run the Fidimag notebooks in your browser.

Alternatively, if you want to run docker from your computer, clone the repository, and run `docker build -t fidimag .` from the main folder (there is a Dockerfile here; do not use the ones in the `docker` folder). This will take a while and will create a Docker container with the name `fidimag` in your computer. To start a server, just type `docker run -v `pwd`:/io -p 30008:8888 fidimag` , which take you to the Docker container, and there you type `jupyter notebook --ip 0.0.0.0 --no-browser --allow-root`. Finally, go to your web browser and type `localhost:30008`.

Otherwise, you need to install Fidimag :) Hope this helps

**Comment by longlong-zhang** [comment]
Hello professor,
  at first ,thanaks for your great pacience to help me tackle this problem.But,sadly i still met some obstacles.
  I followed the recommdation you suggested,for example,i have tried to use Binder.Some of example worked well but some others went wrong. Also, i have attached my error message in this submit.
![微信截图_20200430091517](https://user-images.githubusercontent.com/50805242/80664330-14307100-8ac9-11ea-8a4f-ec8ab3a379d7.png)
 Besides, i have tried your second suggestion,which instruct me to build fidimag in docker. sadely , there emerge a new problem. the error message is just showing in the below screen shoot png.



![微信截图_20200430095306](https://user-images.githubusercontent.com/50805242/80664340-1a265200-8ac9-11ea-9007-b76428a69db6.png)

**Comment by davidcortesortuno** [comment]
I will update Fidimag's version in Binder, version 2.9 still didn't have the steepest descent method. 

Regarding the other problem, it seems a connection failure, maybe because of Windows. I'm not sure, you can try again. Remove the docker images (check images with the command `docker images`, and delete images with `docker rmi --force ID` where ID are the IDs in the previous command.

**Comment by rpep** [comment]
Is there an ‘apt-get update’ in the Docker script David? It looks almost like when it can’t contact the Ubuntu apt package servers because they’re out of date to me

On 30 Apr 2020, at 10:16, David Ignacio Cortes <notifications@github.com> wrote:

﻿

I will update Fidimag's version in Binder, version 2.9 still didn't have the steepest descent method.

Regarding the other problem, it seems a connection failure, maybe because of Windows. I'm not sure, you can try again. Remove the docker images (check images with the command docker images, and delete images with docker rmi --force ID where ID are the IDs in the previous command.

**Comment by davidcortesortuno** [comment]
Yes, there is one at the beginning `RUN apt -y update`. It also runs ok for me, so it must be a connection problem.
