### ISSUE TITLE
set the number of cores used in the simulation.

### ISSUE THREAD

**Issue by Mc210** [computationalmodelling/fidimag#157]
Hi,

 How can I set the number of cores that Fidimag uses to run the simulation?

Thanks

**Comment by davidcortesortuno** [comment]
Hi, in the terminal where you run the simulations, or before running a Jupyter notebook, you can set the `openmp` system variable to control the number of threads by running

```
export OMP_NUM_THREADS=5
```

for example.

**Comment by Mc210** [comment]
Thank you. I have another question,

Do you know if the geometry can be loaded from an external file? I understand that to generate the structure a Ms-function must be built, just like oommf. However, I am trying to generate a curved structure and it takes a few hours to build, (I am considering 800,000 cells).

**Comment by rpep** [comment]
It will depend on your machine somewhat, but generally no. Can you paste the code? I should say that setting Ms/etc. is not done in parallel - only the simulation execution is. If you are adding the demagnetising field then this does add some time to the setup, but 1 hour sounds way too high.

**Comment by davidcortesortuno** [comment]
Maybe you can pickle the Mesh object and save it (using the `dill` library which works better than the `pickle` library)

```python
import dill
from fidimag.common import CuboidMesh

mesh = CuboidMesh(dx=1, dy=1, dz=1, nx=20, ny=20, nz=20)

with open('my_mesh.pkl', 'wb') as F:
    dill.dump(mesh, F)
...
```

Then you should  be able to load this mesh (might take some time):

```python
with open('my_mesh.pkl', 'rb') as F:
    mesh = dill.load(F)

sim = Sim(mesh)
...
```

But, as Ryan said, your mesh seems huge so the demag (if your are using it) might take long time to build the matrices

**Comment by rpep** [comment]
@davidcortesortuno I don't think it's that large - 10e6 is equivalent to 1000 x 1000 x 100 which is certainly quite large, but I'm surprised it's over 1 hour.

**Comment by rpep** [comment]
What exactly are you trying to do? Simulate only a disk?

**Comment by Mc210** [comment]
Hi,
I am trying to build a semi-torus (with a specific thickness). In the definition that you showed, the angular and the inner radius constraint are missing. When redefining the Ms_function, Fidimag continues to take the same time to load the simulation data.

Perhaps in Fidimag it would be good to disable the neighbors' argument when you want to do a micro-magnetic simulation. Since the loops are written in python and not in c. I have redefined that line and now Fidimag takes less than 1 minute to load the simulation. I think everything works fine.

Thank so much

**Comment by rpep** [comment]
In general, this is designed for usability rather than performance, since most simulations take a long time relative to the initialisation cost (which is generally very low - have never seen this issue before). It is possible, though, to set Ms (and other parameters) by passing an array of the appropriate length like:

```python
sim.Ms = array
```
You can also write a faster setter function using Cython similar to the example here:
https://github.com/computationalmodelling/fidimag/tree/master/fidimag/user

Alternatively you can use Numba to do the same sort of thing from within Python. 

In terms of the way we order the array, if your mesh has Nx * Ny * Nz cells, you can get the array index for a particular cell like:
```python
id = k*Nx*Ny + j*Nx + i
```


There is a refactoring going on which moves more code into C/C++ but it's a big work in progress.
