### ISSUE TITLE
 install

### ISSUE THREAD

**Issue by zzzmx-josh** [computationalmodelling/fidimag#163]
Exception Error message 
         -----------------------
         No module named 'six'

         System Info
         -----------------------
         Architecture: x86_64
         Platform: Linux-3.10.0-862.el7.x86_64-x86_64-with-glibc2.17
         Processor: x86_64

**Comment by fangohr** [comment]
There isn’t much context given but it looks like you are missing the Python module ‘six’. Try 

pip install six

**Comment by zzzmx-josh** [comment]
Thank you very much. After installing six, it gives the following errors:
1. make build: 
lib/python3.10/site-packages/setuptools/dist.py:543: UserWarning: The version specified ('3.Xa') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
  warnings.warn(
2. make test: 
/bin/sh: line 1: 26179 Segmentation fault      (core dumped) python3 -m pytest -v -m "not slow and not run_oommf"
make: *** [test] Error 139

wish to solve these problems.

**Comment by mvousden** [comment]
(posting because I've seen this error on a different project, so I may be of value. Caveat emptor: I'm not very closely involved with Fidimag at present)

I reckon that this issue is related to the version of Python you are using - can you explain more about how you installed Python?

If you're not sure, could you help diagnose by running the following in your Python shell, and putting the output here?

```
import platform
platform.platform()  # Underlying distribution and OS
platform.python_version() 
platform.python_implementation()
```

If you're not already, I recommend against using your system Python (system Python = operating system level Python installation, e.g. retrieved with `apt install`) for this project, and instead use an alternative deployment mechanism (e.g. conda [1] or virtualenv [2]), though YMMV.

[1]: https://anaconda.org/anaconda/conda
[2]: https://pypi.org/project/virtualenv/
