### ISSUE TITLE
Testing fails due to an ipython notebook example needs long running time

### ISSUE THREAD

**Issue by ww1g11** [computationalmodelling/fidimag#46]
Sometimes we got "No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself" while the output ends with "isolated_skyrmion.ipynb::Cell 13". I guess this is because the system in the skyrmion example is not small so it takes a lot of time to finish it. So shall we skip the test on this skyrmion example?

**Comment by fangohr** [comment]
I did some timings some time ago (see https://raw.githubusercontent.com/computationalmodelling/fidimag/master/doc/ipynb/runtimes.org). 

We need to make those notebooks run faster (by changing the examples). If we cannot do this, we may have to skip the slower notebooks for testing on travis, but I would prefer to avoid that. If we skipped some, we would have to make sure we run them somewhere regularly, would then have to set up a jenkins server somewhere, etc. 

If we cannot make a notebook run faster (by changing the example), please raise it and we can find a solution together.

Another solution might be to run the normal regression tests on Travis and the notebook testing on Circle CI. However, this is also not ideal (people may be mislead by only looking at travis output to see whether they changes break anything).

**Comment by ww1g11** [comment]
It seems that the most time-consuming part in notebook is not really being tested, for example, in the isolated skyrmion example the relax Cell is marked as "PYTEST_VALIDATE_IGNORE_OUTPUT". Therefore, I would like to suggest to skip this kind of notebook tests. Alternatively, if we can avoid to re-run of the time-consuming Cell marked as "PYTEST_VALIDATE_IGNORE_OUTPUT" (using some kind of buffer mechanism or whatever method), this problem also can be solved.

**Comment by fangohr** [comment]
Thanks, Weiwei. 

Not executing cells marked with PYTEST_VALIDATE_IGNORE_OUTPUT is not likely to be compatible with the nbval idea in the long run. In most nbval notebook tests we use the PYTEST_VALIDATE_IGNORE_OUTPUT flag to ignore output that is likely to change from run to run (due to finite floating point accuracy for example) but we generally still want to execute it because otherwise the cells further down in the notebook are likely to not work.

I think our options are to change the notebooks to run faster, or use some scheme that only runs the fast documentation notebooks as part of the travis continuous integration, and we need to run the others separately. 

The example isolated_skyrmion.ipynb (https://github.com/computationalmodelling/fidimag/blob/master/doc/ipynb/isolated_skyrmion.ipynb) is educational in that it shows a true skyrmionic configuration at the end of the simulation. We may be able to take a coarser mesh and smaller system and save some time to make it taster. Or we could comment out the 'relax' command and do a run_until() for a shorter time, and add a comment to the user that using 'relax' is the recommended way of relaxing the system and we use only the run_until command to reduce computation time. I could imagine that the system pretty much looks like a nice target state long before it is relaxed. So a bit of playing around may find a solution here. I can do this at some point (no power cable at the moment and don't want to run simulations on battery) but if somebody beats me to it, please do ;)

**Comment by ww1g11** [comment]
It seems that some examples can not be changed to run faster, for example, the standard prblem 4, which is also quite time-consuming. 

For the isolated skyrmion, I just re-run the simulation and I found that even using do_precession or not will lead to different results. For example, what I got is not the target state if sim.do_precession is set to False. (If you re-run the isolated_skyrmon example, you also will get this result).
![isolated_skyrmion](https://cloud.githubusercontent.com/assets/12461209/16361235/b18194ae-3bbb-11e6-92b5-46963beae550.jpg)
Certainly, if we relax system starting from some states that close to the target state, we probably will get the target state with sim.do_precession=False. 

I will try to make the skyrmion example run slightly faster, but in the long run, it's better to run this kind of notebook tests separately (only run the fast tests in travis).

**Comment by ww1g11** [comment]
new time records:
========================== slowest 10 test durations ===========================
20.47s call     doc/ipynb/standard_problem_4.ipynb::Cell 19
18.92s call     doc/ipynb/isolated_skyrmion.ipynb::Cell 15
13.62s call     doc/ipynb/standard_problem_4.ipynb::Cell 13
4.81s call     doc/ipynb/current-driven-domain-wall.ipynb::Cell 24
3.54s call     doc/ipynb/spin-waves-in-periodic-system.ipynb::Cell 13
3.51s call     doc/ipynb/tutorial-basics.ipynb::Cell 21
2.03s call     doc/ipynb/current-driven-domain-wall.ipynb::Cell 18
1.77s call     doc/ipynb/spin-polarised-current-driven-skyrmion.ipynb::Cell 14
0.98s teardown doc/ipynb/tutorial-basics.ipynb::Cell 31
0.84s teardown doc/ipynb/1d_domain_wall.ipynb::Cell 15
========================== 65 passed in 82.42 seconds ==========================
