### ISSUE TITLE
[ENH] Increasing Demag Performance

### ISSUE THREAD

**Issue by rpep** [computationalmodelling/fidimag#86]
Looking into the demag calculation, it goes roughly as follows:
- Demag tensor created
  - FFTW Initialised
  - FFTW Plan Created, with arrays to store spin data.
    When the compute_field function is called internally:
  - The magnetisation data is copied into three arrays; one for each component
  - 3-D FFT of each component is taken
  - Convolved with Demag tensor
  - Convolved data transformed back by transforming back
  - Data scaled and copied into an array that Python has passed a pointer to.

I don't think we actually need to do this copying operation, as there is a way of creating a different type of plan which can be created with fftw_create_plan_specific. The FFTW documentation suggests this as the best way of performing FFTW calculations, recommending that specific plans are always used [1]. With this, you can specify padding. 

So we could maybe try:
- create FFTW plan that directly uses the array, rather than copying first. The FFT needs to be done out-of-place, as we don't want to overwrite the spin array. I think we can specify padding in the specific plan, where padding should be = to  (size_of(double) + standard padding by compiler) \* 2
- Perform FFT by directly accessing the spin elements, into the Python created field array with the same padding.
- Convolve this data and then perform an _in-place_ FFT.
- Scale this data appropriately.

**Comment by ryanpepper** [comment]
* Can switch from 3 3-D transforms to one 4-D transform using fftw_plan_many_dft.

**Comment by ryanpepper** [comment]
* Can reduce time to compute demag tensor. Currently we compute all elements by hand, but as the tensor is symmetric, we only need to calculate the upper triangular part, rather than calculating things like Nxx twice. We can then either store the result in both the lower and upper part (with the bonus that we don't need to change any other code) or be slightly more sophisticated and reduce the memory needed.

**Comment by davidcortesortuno** [comment]
For the `4D` transform we can use

```C
fftw_plan fftw_plan_many_dft(int rank, const int *n, int howmany,
                             fftw_complex *in, const int *inembed,
                             int istride, int idist,
                             fftw_complex *out, const int *onembed,
                             int ostride, int odist,
                             int sign, unsigned flags);
```

from the **4.4.1 Advanced Complex DFTs** section of the FFTW doc ( http://www.fftw.org/fftw3.pdf )

**Comment by ryanpepper** [comment]
http://stackoverflow.com/questions/6021740/how-do-i-use-fftw-plan-many-dft-on-a-transposed-array-of-data

Looking at this as an example of what we need to actually do here.

**Comment by ryanpepper** [comment]
To transform the magnetization array directly, rather than doing an expensive copy first, we need to have a byte aligned numpy array. Some suggestions for doing so are here:

http://stackoverflow.com/questions/9895787/memory-alignment-for-fast-fft-in-python-using-shared-arrrays

**Comment by ryanpepper** [comment]
Starting work on this on branch 'improved-demag'. Looking to use the very nice module pyfftw, which takes a lot of the nasty stuff out of everything. Plan for this:
Seperate out into two functions: __init__ sets up data structures and:

i) Creates a buffer to hold magnetisation - demag needs a padded array but clearly other things do not. Can create a slice view to pass to other functions, user, etc.
ii) Creates pyfftw objects (which underneath create FFTW plans).
iii) Compute demag tensor in C. Currently, we store this as 6 separate arrays for each coordinate permutation. Might be better to store this in a single array because the next step is...
iv) Take r2c FT of demag tensor (out-of place destructive).
v) Save FT'd demag tensor at appropriate location (~/.fidimag?)
vi) Save FFTW wisdom.

At each calculation of the demag field (e.g. on a timestep):
i) FT m (out-of-place, non destructive)
i) Take discrete convolution of demag tensor and m in fourier space
ii) take c2r transform to get H_demag (in-place, non-destructive or out-of-place, destructive - depending on this choice will require either one or two buffers. Might be worth trying both approaches to see what results are like on given hardware) with appropriate scaling as FFTW does not by default scale on the inverse FFT (flag in pyfftw).

**Comment by fangohr** [comment]
+1

**Comment by rpep** [comment]
Close for now; spent some time looking into this and could not get meaningful speed improvements. It may be possible to do it by doing a strided in-place transform, which was the last thing I planned to try here.

Much better performance can be achieved by linking with Intel MKL's FFTW wrapper rather than FFTW, but you need to be careful because there are some numerical discrepancies between it and FFTW.
